[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'test/foundry'
cache_path = 'cache/forge-cache'
gas_reports = ["MortgageLoan"]
optimizer = true
optimizer_runs = 4_294_967_295
remappings = ["@openzeppelin/contracts=node_modules/@openzeppelin/contracts/"]
verbosity = 4

# See more config options https://github.com/foundry-rs/foundry/tree/master/config