[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'test/foundry'
cache_path = 'cache/forge-cache'
gas_reports = ["Mortgage"]
optimizer = true
optimizer_runs = 4_294_967_295
remappings = ["@openzeppelin/contracts=node_modules/@openzeppelin/contracts/"]
verbosity = 4

[rpc_endpoints]
h_testnet = "https://testnet.hashio.io/api"
h_mainnet = "https://mainnet.hashio.io/api"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config